<?php

namespace ProductBundle\Repository;

/**
 * CateogryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CateogryRepository extends \Doctrine\ORM\EntityRepository
{
}
