<?php

namespace ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRandom()
    {
        $qb = $this->_em->createQueryBuilder();
        $idList = array();
        $nbProd = $this->createQueryBuilder('i')
            ->select('COUNT(i.id)')
            ->getQuery()->getSingleScalarResult();

        for($i=0; $i<8; $i++)
        {
            $randomId = rand(1, $nbProd);
            if(!in_array($randomId, $idList)) {
                array_push($idList, $randomId);
            }
        }
        //die(var_dump($idList));

        $qb->select('p')
            ->from($this->_entityName, 'p')
            ->where($qb->expr()->in('p.id', $idList))
        ;
        return $qb->getQuery()->getResult();
    }
}
